version: '3'

services:
#  dossier:
#    image: dossier-spring-boot:latest
#    build:
#      context: ../dossier
#    container_name: dossier
#    depends_on:
#      - deal
#    ports:
#      - "8083:8083"
#    networks:
#      - bank
#
#  application:
#    image: application-spring-boot:latest
#    build:
#      context: ../application
#      dockerfile: Dockerfile
#    container_name: application
#    depends_on:
#      - deal
#    ports:
#      - "8082:8082"
#    networks:
#      - bank
#
#  deal:
#    image: deal-spring-boot-postgres:latest
#    build:
#      context: ../deal
#      dockerfile: Dockerfile
#    container_name: deal
#    depends_on:
#      - kafka
#      - db
#      - conveyor
#    ports:
#      - "8080:8080"
#    networks:
#      - bank
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bank_db
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=12345

  conveyor:
    image: conveyor-spring-boot:latest
    build:
      context: ../conveyor
      dockerfile: Dockerfile
    container_name: conveyor
    ports:
      - "8081:8081"
    networks:
      - bank

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - bank

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    networks:
      - bank
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  db:
    image: postgres:13.1-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=bank_db
    ports:
      - "5432:5432"
    networks:
      - bank

networks:
  bank:
    driver: bridge